### ISSUE TITLE
Create a 'develop' for Tutorial repo

### ISSUE THREAD

**Issue by lisatiberio** [TASBE/TASBEFlowAnalytics#103]
The TASBEFlowAnalytics-Tutorial repository needs a 'develop' to push changes against.

**Comment by lisatiberio** [comment]
I have created a 'develop' branch and pushed it to origin.

**Comment by jakebeal** [comment]
Looks like I had also created a develop branch, but accidentally pushed it to my old (pre-TASBE) version; I've fixed my config now, and updated the develop.  There should be no conflicts, since all of my changes were just enhancing comments.
