### ISSUE TITLE
plus-minus comparison template should have variable batch size

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#105]
We often want to compare sets not just of +/- but something like +/-/control or A/B/C/D.
It would be useful to have the ability to get automated comparisons with this type of variable batching rather than to kludge it in.

**Comment by coverney** [comment]
This must involve editing ```process_plusminus_batch.m``` such that it can take in more than just sets of +/-? We would then just create more ```experiment_names``` and other necessary variables to build the ```pm_sampleresults```.

**Comment by jakebeal** [comment]
Yes, I think this is correct --- it would probably also undo one of the checks you've just added in, but that's OK when it's an upgrade to add it and an upgrade for a different reason to remove it.

**Comment by coverney** [comment]
I could create a preference that determines whether there are more than 2 batches and then if that preference is true, modify the way I check the batch size of the batch_description in the process file.

**Comment by jakebeal** [comment]
I would suggest the following:
- In the batch definition, we allow a cell array of "batch names", such as `{'plus', 'minus'}` or `{'plus','minus','control'}` or `{'A','B','C','D'}`.  Then you can check to make sure the batch count matches the batch name count.
- If we can reasonably make this optional, then when there are precisely two batches, we default to `{'plus','minus'}` --> but if this doesn't work well, we can just make it required and update the template.
- For all cross-batch comparisons (e.g., fold ratio, SNR), we compare everything against the last batch (might want to change that later)

**Comment by coverney** [comment]
For the third point, do you mean that for any cross-batch comparison we would not check for all combinations between the batches if there are more than 2?

**Comment by jakebeal** [comment]
That's my initial thought, though it might want to be revisited in the future, depending on use cases. The idea is that we've got a "baseline" that we're comparing several different treatments to, and so we get N-1 comparisons for N treatments, rather than N*(N-1)

**Comment by coverney** [comment]
Sounds good!

**Comment by coverney** [comment]
Also, I just realized that one could have more than two categories (i.e. Highs and Lows) so I will change the plusminus size checks accordingly.
