### ISSUE TITLE
Bead peaks identified as 2 to 7 of 6

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#111]
The report on bead peak matching appears to be reporting incorrectly, with statements such as:

> Bead peaks identified as 2 to 7 of 6

**Comment by lisatiberio** [comment]
Is this happening in the Matlab code or the Octave code?  I thought I had fixed this problem with the Octave code.

**Comment by jakebeal** [comment]
I have not checked in Octave; I have seen this in Matlab.

**Comment by lisatiberio** [comment]
I just ran both the Matlab and Octave unit tests and did not see this problem.  Maybe there is different output when we are not running headless?

**Comment by lisatiberio** [comment]
I just ran the exercises in the Tutorial repository.  I did not see this error.  I thought I had fixed this issue earlier.  I cannot duplicate this problem.

**Comment by jakebeal** [comment]
I will see if I can reproduce it again; it's possible that the updates that have happened have rendered it moot.

**Comment by jakebeal** [comment]
Closing as duplicate of #134
