### ISSUE TITLE
Remove randomness from gate building

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#114]
GMM Gates are built with the aid of a gradient descent starting from a random seed (the usual fitting method). This means, however, that rebuilding a gate often ends up with minor changes in its values, and thus in the values of data processed with it.  It would be good to remove this in order to ensure more precise reproducibility in the statistics of small subpopulations.

**Comment by jakebeal** [comment]
Note that this is now causing sporadic test failures, and thus is an annoying problem already.

**Comment by coverney** [comment]
I looked through the ```GMMGating.m``` code and wanted to double check if the random seed is automatically generated via the following line
```dist = fitgmdist(channel_data,AGP.k_components,'Regularize',1e-5);```

Would a potential solution be controlling random number generation with a ```rng``` (https://www.mathworks.com/help/matlab/ref/rng.html)?

**Comment by jakebeal** [comment]
I think that controlling the random seed is the right way to fix it.  Probably we should add a TASBEConfig for whether we use a fixed seed or not, defaulting to use of a fixed seed.

I'm not sure exactly where to set the seed, but expect you can probably figure that out with a bit of investigation and experimentations.

**Comment by coverney** [comment]
I did some more research and tested out a bunch of different GMM distributions from ```fitgmdist```. I don't think we will be able to use ```rng(s)``` because the randomization occurs within Matlab's ```fitgmdist``` function. Instead, I found a 'Start' initial value setting parameter within ```fitgmdist```. Currently, its value is 'plus', which selects the centroids at random. A few other alternatives include inputting (1) a vector of integers containing an initial guess of the component index for each point or (2) a structure array with initial means, an initial covariance matrix, and initial component proportions. 

I was wondering if we should consider implementing any of those alternatives. I did some initial testing and creating a structure array successfully eliminates the randomness. The problem is: I am not sure what exactly to put into the structure array/ vector array.

**Comment by coverney** [comment]
Currently, I am using the vector of integers approach and my initial guess is that the first half of ```channel_data``` belongs in one component while the second half belongs in another component. Though those guesses are probably very off, I am consistently getting the following results from ```fitgmdist```:

mu: 
```[5.11161625707655	3.40868603816900; 4.55461443914258	3.34260163825510]```
Sigma: 
```
val(:, :, 1) = [0.0130    0.0149; 0.0149    0.0328]
val(:, :, 2) = [0.2054    0.0548; 0.0548    0.0515]
```
ComponentProportion
```[0.878446005741684	0.121553994258316]```

**Comment by coverney** [comment]
Resources that I used: https://www.mathworks.com/help/stats/fitgmdist.html#bugncox-1

**Comment by jakebeal** [comment]
If it's a good fit, the starting point shouldn't significantly matter.  The number of components is variable, though, so try an integer vector that initially puts everything in the first component?

**Comment by coverney** [comment]
According to matlab, the vector of integers should range from 1 to the number of components. I was thinking we could break up the vector into n sections and assign the values in each section as the section number.

**Comment by jakebeal** [comment]
That's fine: just make sure it will work for n=1 as well as n>1

**Comment by coverney** [comment]
I am going to try to use a structure array with initial mu, sigma, and component proportion values as the start parameter instead.

**Comment by coverney** [comment]
I tried using ```rng``` again and after testing it a bunch of times I got consistent values for mu, Sigma, and ComponentProportion. Octave does not have a ```rng``` function, but it has an equivalent in the form of ```rand ("seed", val)```.

**Comment by coverney** [comment]
I am going to rerun the build a few times to see if I will get any randomness in GMGating.

**Comment by jakebeal** [comment]
Great!  If you see the exact same numbers twice, you've probably already got a solution, since there were always at least small differences, just only occasionally large enough to trigger problems in the test.

**Comment by coverney** [comment]
I tested GMGating with Octave and consistently got the following Mu values:
```
5.1116	3.4086
4.5542	3.3428
```
I think this issue has been addressed, and we can re-open it in case the randomness arises again in Travis?

**Comment by jakebeal** [comment]
Sounds good --- I will approve the pull request and close this issue when the checks complete.
