### ISSUE TITLE
Confirm units are correct in CSVs

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#125]
Make sure that the CSV outputs have the right units for both successful and failed calibrations.

**Comment by jakebeal** [comment]
CSV outputs currently are not showing units.  They should be incorporated from the channel information of the color model into the row names (likely with sanititization needed)

**Comment by lisatiberio** [comment]
Hi Jake,
I want to check my understanding.  Does the calibration process occurs in function beads_to_ERF?  If that is the case, it is called (in resolve) if 'override_units' is not set.  Isn't that backwards?  Wouldn't calibration need to happen first and then check for 'override_units' being set?
Lisa

**Comment by jakebeal** [comment]
override_units is most often used when processing data for which the bead sample is missing or unusable. In these cases, the calibration process cannot complete and needs to be preempted.
