### ISSUE TITLE
Unify processing settings, expose interface

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#127]
Processing settings are currently run with two different interfaces: TASBESettings and TASBEConfig
All uses of TASBESettings should be migrated into TASBEConfig, along with reasonable default values.

**Comment by jakebeal** [comment]
I noticed another batch I had forgotten about also: OutputSettings

**Comment by lisatiberio** [comment]
Should I do the new batch in the same branch?

**Comment by jakebeal** [comment]
Sure --- I thought you might want do, so didn't delete after merge.  
Also: have you thought about how to best expose the interface to polling by the wrapper?

**Comment by jakebeal** [comment]
Fixed as of #184
