### ISSUE TITLE
OS -> OutputSettings

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#138]
The OS abbreviation in TASBEConfig should be expanded back out to OutputSettings.

**Comment by jakebeal** [comment]
Moving this to triage 0 because it should be very simple and I'd like to include it in the 5.0 release.

**Comment by lisatiberio** [comment]
Finished migrating the commented lines to using TASBEConfig.  I just pushed my ltiberio.issue127 branch.

**Comment by jakebeal** [comment]
Thank you --- this issue is referring to a different thing, however: I would like to change, for example, `'OS.FixedAxis'` to be `'OutputSettings.FixedAxis'`

**Comment by jakebeal** [comment]
Completed in #185, #191
