### ISSUE TITLE
Tutorial needs CI

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#139]
The https://github.com/TASBE/TASBEFlowAnalytics-Tutorial/ repository also should get integrated with Travis to validate that its templates are working correctly.

**Comment by jakebeal** [comment]
Also, the "lesson" .m files

**Comment by coverney** [comment]
Only people with ownership of the tutorial branch can activate Travis CI for it. I wrote a tentative ```.travis.yml``` file but still need to test it.

**Comment by jakebeal** [comment]
Hi, Cassandra: I've now set it up and triggered the first build.  You should be able to work with Travis on the tutorial now: https://travis-ci.org/TASBE/TASBEFlowAnalytics-Tutorial

**Comment by jakebeal** [comment]
To finalize:

1. Pull the working version into the develop and then master.
2. Link the Travis badge from the TASBEFlowAnalytics and tutorial readmes.

**Comment by jakebeal** [comment]
Also, retarget the travis pull to use the master, rather than coverney.excel

**Comment by coverney** [comment]
Completed with pull request #345
