### ISSUE TITLE
Fold AnalysisParameters into TASBEConfig

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#141]
AnalysisParameters looks like another candidate for folding into TASBEConfig. Need to check use cases to see if there will be any problems in doing so.

**Comment by jakebeal** [comment]
This looks like there will indeed be some complications, so deferring it for a later release.

**Comment by coverney** [comment]
Would this involve going through all of the files, checking to see if any of the functions in ```@Analysis Parameters``` get called and then changing them to TASBEConfig setters and getters accordingly?

**Comment by jakebeal** [comment]
Yes --- the complications will likely come through the fact that there are some places where we are abusing AnalysisParameters.  For example, batch analysis fabricates multiple copies of analysis parameters to kludge a one-channel-at-a-time analysis.  This is definitely the wrong way to do batch analysis (and links to some of our other issues too), but means the fix for this issue will touch other code as well.

**Comment by coverney** [comment]
I see. Then I will start tackling this after I figure out how to move some other preferences to TASBEConfig.

**Comment by jakebeal** [comment]
Actually, I think we're going to end up going the opposite direction, expanding AnalysisParameters to configure new workflows per #442
