### ISSUE TITLE
Matlab dependency for Statistics package

### ISSUE THREAD

**Issue by mehersam** [TASBE/TASBEFlowAnalytics#15]
autodetect_gating function used to make a color model relies on the statistics toolbox within matlab to create a gaussian model distribution.

**Comment by jakebeal** [comment]
Clarification: in particular the gmdistribution object is the problem dependency.  This should be OK in Octave, but fails for vanilla Matlab.

**Comment by jakebeal** [comment]
Corrected in pull #17
