### ISSUE TITLE
Standard deviation in CSV exports

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#155]
CSV exports should include (and distinguish) both standard deviation of means and standard deviation of events.

**Comment by lisatiberio** [comment]
Currently writeStatisticsCsv writes "geo" means and "geo" standard deviations.  I'm not sure what a "geo" standard deviation is, or how it relates to standard deviation of means or events.

**Comment by jakebeal** [comment]
geo = geometric, i.e., means and standard deviations on the log scale rather than linear scale.  It's orthogonal to standard deviation of means vs. events.  Almost all of our statistics are geometric, rather than arithmetic because everything is log scale.

**Comment by jakebeal** [comment]
Current CSV statistics exports are only per-sample, and thus the std-of-means is not meaningful. We will likely want to revisit this in the future, but not yet.
