### ISSUE TITLE
sig figs in CSV exports

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#156]
Currently, CSV exports are being done in floating point notation with no limit on significant figures.
We should use scientific notation for the means and limit both means and standard deviations to 3 sig figs.

**Comment by lisatiberio** [comment]
Do you mean 3 digits to the right of the decimal, or should I round all of the numbers?

**Comment by jakebeal** [comment]
I was thinking 3 to the right of the decimal.  Probably we should make the number of sigfigs something that can be set by a config as well.

**Comment by zyndagj** [comment]
It has been a while since I have done actual significant figures, but they usually correspond to the accuracy of your measurements. Is the goal here to represent a certain number of digits you can trust, or simply standardize and clean up the output?

**Comment by jakebeal** [comment]
We're making a conservative heuristic guess about supportable accuracy. With geometric statistics on a flow cytometer, measurements are typically repeatable to at least one decimal place (e.g., 1.7-fold), which would typically tell us to report one additional digit (e.g., 1.76-fold). To be conservative, we'll add one more for the default level of reporting (e.g., 1.763-fold)

Let us, however, make the number of significant figures configurable via TASBEConfig, so that it can be adjusted away from this if need.  The default for this can then be set at 4 sigfigs.
