### ISSUE TITLE
Error setting low number of bins in plusminus

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#163]
Trying to set one or two bins by changing 
`bins = BinSequence(4,0.1,10,'log_bins');`
to `bins = BinSequence(6,4,10,'log_bins');` or `bins = BinSequence(2,4,10,'log_bins');` results in matrix dimension errors like (with one bin): 

> Assignment has more non-singleton rhs dimensions than non-singleton subscripts
> 
> Error in compute_sample_statistics (line 51)
>     histograms(:,k) = hist(log10(data(pos,k)),log10(bin_centers));
> 
> Error in process_data (line 34)
>         sampleresults{i}{j} = compute_sample_statistics(colorModel,experiment,fileName,analysisParams,data);
> 
> Error in process_plusminus_batch (line 41)
>     p_sampleresults = process_data(colorModel,p_experiment,analysisParams);
> 
> Error in analyze_plusminus_HT168 (line 148)
> [results sampleresults] = process_plusminus_batch( CM, batch_description, AP, OSbin);

or (two bins):

> Warning: Problematic distribution: no peaks found in histogram 
>  In find_peaks (line 39)
>   In compute_sample_statistics (line 54)
>   In process_data (line 34)
>   In process_plusminus_batch (line 41)
>   In analyze_plusminus_HT168 (line 148) 
> Index exceeds matrix dimensions.
> 
> Error in summarize_data (line 137)
>         if sum(valid(j,:))==0,
> 
> Error in process_plusminus_batch (line 42)
>     p_results = summarize_data(colorModel,p_experiment,analysisParams,p_sampleresults);
> 
> Error in analyze_plusminus_HT168 (line 148)
> [results sampleresults] = process_plusminus_batch( CM, batch_description,

**Comment by jakebeal** [comment]
I have a fix for this validating right now, which supports at least the two-bin case and is tested successfully on experiment HT168.  Please note, however, that the statistics of a large bin are not the same as the statistics over statistics of large bins: some values like SNR will be much lower because things are getting smeared together.

**Comment by jakebeal** [comment]
Looks like it should work for the one-bin case as well, based on my tests so far.  The `develop` branch now contains this fix.  It won't make it into a release for a little while as we're sorting out some unrelated issues.
