### ISSUE TITLE
bead conversion assumes 7-peak series

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#20]
The MEFL bead conversion currently assumes there are precisely 7 peaks, which is not necessarily correct.

**Comment by lisatiberio** [comment]
Jake, is the correct number of peaks determined by how many values in PeakMEFLs are not NaNs?

**Comment by jakebeal** [comment]
I will answer in terms of the BeadCatalog.xlsx file --- the NaNs are an artifact by the reading process, and might get adjusted.

In the file, bead peak information begins at column F.  Sometimes the early peaks are not quantified, and as such they are given blanks --- they can be detected and are legitimate, but should be ignored during the fitting process.  The numbers then continue until the top peak, after which it is blank.  The expected number of peaks, then, is the number of columns from F to the highest number in the row.

For example:
- SpheroTech RCP-30-5A, Lot AG01, PE-Cy7: there are 8 peaks, but only the top 3 are quantified.
- SpheroTech URCP-38-2K, Lot AG01, FITC: there are 6 peaks, but only the top 5 are quantified.

**Comment by lisatiberio** [comment]
I have figured out the source of my confusion.  In the file test_beakpeaks, the function test_twopeaks has UT.first_peak = 7.  Does that 7 refer to the last value in the quantified array of peak values or the second to last value in the non-quantified array of peak values?

**Comment by jakebeal** [comment]
Actually, neither: it refers to the second-to-last value in the quantified array (i.e., PeakMEFLs).

There are 8 peaks, but the quantified array has only 7 values since the bottom one was not quantified. Thus the first entry in the quantified array is "peak 2" and its second-to-last entry (referred to here) is "peak 7".

**Comment by jakebeal** [comment]
Resolved with #104
