### ISSUE TITLE
Proper help docs for all functions

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#203]
Not all functions have help documentation, and for many the help comments don't show up when you run the matlab help comment.

**Comment by coverney** [comment]
Should we update "Copyright (C) 2010-2017" to "Copyright (C) 2010-2018"?

**Comment by jakebeal** [comment]
Might as well, for anything you touch that's ours (don't mess with the files that are imported from other libraries, though those should all be in their own directory).  There's probably a better way to deal with it on all the files, but I don't know good automation for it.

**Comment by coverney** [comment]
Completed! Changes in next pull request.
