### ISSUE TITLE
plusminus script taking a long time?

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#209]
The script seems to hang for a noticeably longer time after "Computing comparison for (last device)..." I'm not sure if this is because I've changed things in my code or wasn't paying as close attention as before, but analyses seem to be taking longer to run I think.

**Comment by jakebeal** [comment]
Can you give some measure of how long it's taking for a given number of conditions?

**Comment by bhwein** [comment]
I'll time it next time I run a plus/minus

**Comment by jakebeal** [comment]
This doesn't seem to have remained an issue, so I'm going to close it; if this concern comes up again, please re-open.
