### ISSUE TITLE
plot_batch_histograms should default to color model colors

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#214]
From an observation in #208: the color options to plot_batch_histograms are generally redundant to the specification of line colors in the color model.  We should have it default to color model colors rather than requiring line colors.

**Comment by coverney** [comment]
I think I know how to fix this issue by correcting ```plot_batch_histograms.m``` and the batch analysis templates. If this sounds like a reasonable approach, I would be happy to assign this issue to myself.

**Comment by coverney** [comment]
I tested this out, and it works. I am not sure whether to actually write a test for this.

**Comment by jakebeal** [comment]
I think this is one of those GUI things that we don't have a good automated test for.  The updates that you made to the current tests are good enough, I think.

**Comment by jakebeal** [comment]
I'm afraid that the current solution turns out to only work when the set and order in which the colors were analyzed for `per_color_constitutive_analysis` is identical to the colors in the colormodel.

To reproduce the bug, change the template from:
''''
[results sampleresults] = per_color_constitutive_analysis(CM,file_pairs,{'EBFP2','EYFP','mKate'},AP);
''''
to
''''
[results sampleresults] = per_color_constitutive_analysis(CM,file_pairs,{'mKate','EBFP2','EYFP'},AP);
''''
and to
''''
[results sampleresults] = per_color_constitutive_analysis(CM,file_pairs,{'mKate','EBFP2'},AP);
''''
Observe that for 1) the lines change color when they shouldn't, and for 2) we get an error.

**Comment by coverney** [comment]
That is interesting. I will delve into this issue right now.

**Comment by coverney** [comment]
I fixed the plotting problem by using another method to obtain the channel information. I also found that ```serializeBatchOutput``` and ```writeStatisticsCsv``` have similar problems and would error when we only pass in two channel names into ```per_color_constitutive_analysis```. I was wondering if I could modify those functions as well so the CSV files would only contain information for the channels that we specified in ```per_color_constitutive_analysis```.

**Comment by jakebeal** [comment]
Yes, please do make those modifications as well!

The bug has not yet been exercised yet only because the use it's being put to always has a 1:1 match between color model and batch analysis.

**Comment by coverney** [comment]
Great! I will make those changes as soon as my VPN connection is working again. (I am having some trouble establishing a stable connection to my school's VPN to access Matlab.)
