### ISSUE TITLE
Error running colormodel w/ version 6.0

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#219]
I am encountering this error now when I make the color model:

Error using regexp
The 'STRING' input must be either a char row vector, a cell array of char row vectors, or a string array.

Error in strsplit (line 125)
[c, matches] = regexp(str, aDelim, 'split', 'match');

Error in tasbe_version (line 26)
strs = strsplit(raw_version,'.');

Error in ColorModel (line 15)
        CM.version = tasbe_version();

Error in make_color_model (line 44)
CM = ColorModel(stemBeads, stemBlank, channels, colorfiles, colorpairfiles);

**Comment by jakebeal** [comment]
I am not being able to reproduce this.  Can you please turn on "stop on errors" and let me know what's read in raw_version?

I am guessing that one of two things happened: 1) you've somehow got a conflict in your checkout, which is putting garbled material into the version file, or 2) there's something going wrong in the path.

**Comment by bhwein** [comment]
val =


    '<<<<<<<      '
    'HEAD         '
    '6.0.0        '
    '=======      '
    '5.0.0        '
    '>>>>>>>      '
    'parent       '
    'of           '
    '1bdfec9...   '
    'Merge        '
    'pull         '
    'request      '
    '#206         '
    'from         '
    'TASBE/develop'

**Comment by bhwein** [comment]
Hi Jake,
I get this error now:
Undefined function or variable 'smoothhist2D'.

Error in GMMGating (line 128)
    smoothhist2D([channel_data(:,i) channel_data(:,i+1)],5,[500, 500],[],type,AGP.range,AGP.largeoutliers);

Error in make_color_model_HT152 (line 26)
autogate = GMMGating(stemBlank,AGP,'plots');

**Comment by bhwein** [comment]
I did a clean out

**Comment by jakebeal** [comment]
(again: I cannot replicate --- I literally just finished running a make_color_model on another data set with exactly the same form)

**Comment by jakebeal** [comment]
If you didn't run the installer script, you won't have gotten the updated paths.

**Comment by jakebeal** [comment]
Run 'make install' and try again; that will likely fix it.

**Comment by bhwein** [comment]
I figured out the problem. I had put TASBEFlowAnalytics folder in my general path under "Set Path" so that I didn't need to add it every time I open MATLAB. Since you added the library_code folder, the scripts in it were not in the path.

**Comment by jakebeal** [comment]
OK, glad you got it sorted.  This should have been able to be sorted out by its installer, but if you were setting paths by hand, that would definitely lead to this problem.
