### ISSUE TITLE
Error in creating post filter. add_postfilter cannot input RangeFilter type arguments

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#221]
```
Undefined function 'add_postfilter' for input arguments of type 'RangeFilter'.

Error in analyze_batch_HT173 (line 7)
CM = add_postfilter(CM,RangeFilter('BFP-A',[1e6 inf]));
```

**Comment by bhwein** [comment]
The filter seems to be working using the tutorial data, but one thing I noticed that is different is that when I load my CM is being converted to a struct rather than CM object, whereas, the tutorial CM loads fine. I have no idea if this is related to the filter warning.
```
load('../colormodel/CM-HT173.mat');
Warning: Fields of object 'CM' do not match the current constructor definition for
class 'ColorModel'.  The object has been converted to a structure. 
```

**Comment by bhwein** [comment]
Ok, rerunning the colormodel script fixed everything. I wonder what was wrong with the CM.

**Comment by jakebeal** [comment]
When the ColorModel class fields update, old saved objects are no longer compatible and get loaded as structs instead. Thus, when you regenerated with 6.0, it worked again. 

A major version number change indicates something that is not backward compatible (per [semantic versioning](https://semver.org/)), so when we update the major version number (e.g., 5.1 to 6.0), you should expect this may happen and thus to need to regenerate models accordingly.  When we update minor version numbers (e.g., 5.0 to 5.1), the change should be backward compatible and not cause any such issues.
