### ISSUE TITLE
Plus-minus bin count histograms

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#222]
Feature request: It would be great to for the plusminus script to produce bin count plots with both plus and minus states overlayed (and additionally a blank sample). See attached image for mockup:
<img width="759" alt="diagram" src="https://user-images.githubusercontent.com/28678480/38178578-b86a120e-35e3-11e8-92bd-d9a5581c7800.png">

**Comment by jakebeal** [comment]
You're thinking pure output MEFL distribution and not parametric in constitutive?

**Comment by jakebeal** [comment]
This is quite doable.  For prioritization purposes vs other upgrades: do you have any specific thing you need to have this for by a specific date?

**Comment by bhwein** [comment]
I don't want to put too much pressure on you. I am feeling that there will be people at my defense on Tuesday that will ask me for this information. My experience presenting this type of data is that people really want to know how many cells are switched or not-switched. The parametric constitutive vs. mean OFP is good and the pop. standard deviation sort of tells you this but it won't necessary tell you if the populations are unimodal and smeary vs. bimodal and tight. Side-question: is there a statistical metric that tells you the modality of a distribution?

**Comment by bhwein** [comment]
I might just whip up some plots in FlowJo for some selected systems.

**Comment by jakebeal** [comment]
The gaussian-mixture model fit can tell you something about unimodal vs. bimodal.

With regards to showing things at your defense: I would suggest that rather than putting a dependency on me, you can kludge that now using the batch_analysis template to and superposing the resulting distribution plots.

**Comment by jakebeal** [comment]
Plan for resolution: set up an overlay histograms functionality for batch analyses.
