### ISSUE TITLE
"-name" plots when OutputSettings.StemName is empty

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#239]
When running and plotting batch analyses, the figures are named with:

`[TASBEConfig.get('OutputSettings.StemName') '-' results{i}.condition '-bincounts']`

This means that if one just wants a list of conditions and sets `OutputSettings.StemName` to be empty, you end up with plots starting with "-", which is ugly.  We should make it not put the hyphen in if the stem-name is empty.

This might apply to other plots too.

**Comment by coverney** [comment]
submitted a pull request
