### ISSUE TITLE
ColorModel and Analysis not working on older Matlab versions

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#256]
I found that I was not able to generate a ColorModel while using a 2013b version of Matlab. The errors I received include: 
```In GMMGating.GMMGating at 66 
Error using eig
Out of memory

**Comment by jakebeal** [comment]
That's a very strange error to be getting... can you post the rest of the stack trace too see where it's originating?

**Comment by coverney** [comment]
I think the error I mentioned above actually happens because of a compatibility issue between Mac and the 2013b version of Matlab. I installed the same version on a PC, and it did not have this problem. However, I still can not run any analysis because of the cluster function. The error says ```Undefined function 'cluster' for input arguments of type 'double'.```

**Comment by coverney** [comment]
It is called in ```applyFilter.m``` on line 23. 
```clustered = cluster(GMMG.distribution,channel_data);```

**Comment by jakebeal** [comment]
Can you check and see whether your Matlab has the stats toolbox gmdistribution function?
Run `which gmdistribution` and see whether it's using the Matlab version or the copy distributed with TASBE. If it's using the Matlab version, then maybe there's an interface difference/problem.

**Comment by coverney** [comment]
It is using the gmdistribution from the TASBE folder.

**Comment by jakebeal** [comment]
That's very odd then... worth digging into more later.

**Comment by jakebeal** [comment]
@coverney Can you please re-try this with a current version of TASBE?  I'd like to see whether it's still a live issue.

**Comment by coverney** [comment]
I ran all of the templates, and they worked, so I think this issue can be closed now. I wonder how this issue got resolved.

**Comment by jakebeal** [comment]
I'm guessing that it was something about the path setups and refactoring that we did.  In any case, I will close it since it appears to be resolved.
