### ISSUE TITLE
GettingStarted Document

### ISSUE THREAD

**Issue by mehersam** [TASBE/TASBEFlowAnalytics#27]
A document that includes 

  - how to download the TASBEFlowAnalytics
  - how does each user reset paths for their environment 
  - redirect to a document of how to make a CM and perform a batch analysis

**Comment by mehersam** [comment]
[tasbe-started-tutorial.pdf](https://github.com/TASBE/TASBEFlowAnalytics/files/1157124/tasbe-started-tutorial.pdf)

**Comment by mehersam** [comment]
Need to fix titles and some grammar

**Comment by mehersam** [comment]
https://github.com/mehersam/TASBEFlowAnalytics/blob/gh-pages/docs/GettingStarted/tasbe-getting-started-tutorial.pdf

**Comment by coverney** [comment]
Incorporated into website: https://tasbe.github.io/TASBE/docs/installation.html
