### ISSUE TITLE
Use Case Document

### ISSUE THREAD

**Issue by mehersam** [TASBE/TASBEFlowAnalytics#28]
A document that follows how to use the TASBE tool, explains useful functions and how to use them. 

- Explain what is a color model 
- How to build a color model
- what are each of the functions within the color model 
- what do the outputs mean
- Extra section just explaining how threshold, bead_min, max, etc...

**Comment by mehersam** [comment]
[tasbe-color-model.pdf](https://github.com/TASBE/TASBEFlowAnalytics/files/1163556/tasbe-color-model.pdf)

**Comment by coverney** [comment]
Incorporated into website: https://tasbe.github.io/TASBE/docs/color_model.html
