### ISSUE TITLE
Show Excel filenames generated

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#283]
In the Excel template file, show the filenames that are generated from the template in a column to the right to the samples table.

This might also mean moving the template generation from Matlab back to Excel to better support use on Mac, which should be possible with VBA.

**Comment by jakebeal** [comment]
Let's try it and see...

**Comment by coverney** [comment]
Finished first attempt at this issue. Some things that I want to work on if I have some more time:
- Clear previous filename cells before adding the new ones (applicable if going from 2+ replicates to 1)
- Run the UpdateFilename macro in other sheets (tried to figure this one out but kept getting the mysterious 400 error).

**Comment by coverney** [comment]
Completed both of the tasks mentioned above.

**Comment by coverney** [comment]
Implicitly tested via color model and batch analysis.
