### ISSUE TITLE
Excel progress bar?

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#285]
Can we show some sort of progress bar for how far the Matlab session has run when running in Excel?

**Comment by coverney** [comment]
Great news!! I was able to get this working for the Calibration tab, and I have an idea for the Cancel button. Things are looking very bright!

**Comment by coverney** [comment]
I implemented multithreading for the other analysis functions and refined the progress bar. This feature is basically complete, but I won't close this issue until I give a demo.

**Comment by coverney** [comment]
Also, I plan to do some more testing tomorrow morning.

**Comment by coverney** [comment]
Completed first pass for this issue. It is ready for user input/testing. Changes are in next pull request (339). There are still some rare cases when the final msgbox doesn't appear, but I was not able to identify the cause.
