### ISSUE TITLE
Excel plus/minus or transfer curve w. 2 or 4 colors

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#287]
Make sure the Excel interface can operate appropriately when there are 2 or 4 colors for plus/minus or transfercurve analysis.  These are kludges.

In particular:
- With 2 colors, one should be constitutive, and the other should be used for both input and output, no matter whether it's labeled as input or output.
- With 4 colors, we should allow one to be ignored or we should run twice, doubling input or doubling output.

**Comment by coverney** [comment]
Added tests, changes will be in next pull request.
