### ISSUE TITLE
Excel sheet interface for comparing bead files

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#288]
There should be an Excel sheet interface for validating that multiple bead files are comparable.
Maybe it should happen automatically if you put more than one sample into the beads field?

**Comment by coverney** [comment]
I was wondering what would happen if the beadfiles are not identical to each other. Should a warning/ error be thrown? Also, I am assuming that the first beadfile will be used as a default, or there could be a column in "Samples" that could indicate which samples are associated with which beadfiles, so multiple color models can be created and used for a single template.

**Comment by jakebeal** [comment]
I think that we should use the first beadfile to build the color model (and document that).

Then if the others don't match, I agree that we should throw a warning/error.

**Comment by coverney** [comment]
Tested via color model.
