### ISSUE TITLE
Excel interface: generate plates from samples

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#289]
There should be a button to fill in the "plate" tables from the samples tab.  

If there is a "plate" column, we should also see how many plates are listed, and generate one for each.

**Comment by coverney** [comment]
The inputs in the plate column could be the type of plate followed by plate number (i.e. 96w,1). We would then use the sample location to put the sample name where it needs to be on the plate. Does that sound reasonable?

**Comment by jakebeal** [comment]
Sounds like a good first pass --- try it out, and let's see what the lab folks think.

**Comment by coverney** [comment]
I was able to get this working using the idea mentioned above. A few things that I want to add include
- Getting this to work with replicates (this involves first splitting the sample location by commas and then splitting them further into characters)
- Clearing the plates before re-populating them.

The second point brings me to the following question: should there be a clear plate button or should the plates by cleared automatically before being populated? If the clearing process is done automatically, should all of the plates be cleared or just the one that is being filled out?

**Comment by jakebeal** [comment]
Replicate splitting is definitely a must-have.
As for plate repopulation: my guess would be that it should all occur as a batch, without the need for a separate "clear" button.

**Comment by coverney** [comment]
Completed, in the updated batch template in Tutorial repo. I accomplished the two points mentioned in the above comment. Also made the plate layout cells protected.
