### ISSUE TITLE
Excel Interface: drop down menus

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#297]
A potential user interface feature: Incorporate drop-down menus when inputting sample column names and key values for analysis

**Comment by coverney** [comment]
Potentially helpful reference: https://www.excel-easy.com/vba/examples/combo-box.html

**Comment by coverney** [comment]
A really useful resource: https://www.thespreadsheetguru.com/blog/2014/5/14/vba-for-excels-form-control-combo-boxes

**Comment by coverney** [comment]
Reference to change the formatting of combo box: https://www.ozgrid.com/forum/index.php?thread/63992-change-font-size-of-combo-box/

**Comment by coverney** [comment]
I think this issue is done via https://github.com/TASBE/TASBEFlowAnalytics-Tutorial/pull/79?

**Comment by jakebeal** [comment]
Agreed.
