### ISSUE TITLE
Excel Interface: expand TASBESession log to include more errors

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#298]
Make TASBESession log include other Matlab errors.

**Comment by jakebeal** [comment]
A note on implementation: since many Matlab errors may be from libraries or system calls and can't be logged to TASBESession directly, a good way to do this may be with a try/catch block at the top level of `analyzeFromExcel`.

**Comment by coverney** [comment]
Done: added try/catch block to convert Matlab error to TASBESession error.

**Comment by coverney** [comment]
Can write a quick test for this by just forcing an error in ```analyzeFromExcel```.

**Comment by coverney** [comment]
Finished test
