### ISSUE TITLE
Test core Excel functionality

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#299]
We need at least a smoke-test that the basic Excel functionality is working in some capacity.

**Comment by coverney** [comment]
I am having problems getting Octave to work with my excel functions because Octave does not like calling ```java.io.File```. The error says "unable to find Java Runtime Environment". I was wondering if you have had any experience with this.

**Comment by coverney** [comment]
I was also wondering how I can get the build to install and use the io package for xlsread.

**Comment by jakebeal** [comment]
I believe you should be able to install it from the zip in the matlab_compat directory.  This is what the .travis.yml file does:

`octave --no-gui --quiet --eval "pkg install matlab_compat/io-2.4.10.tar.gz"`

**Comment by coverney** [comment]
I added the following to the .travis.yml file:
```
- octave --no-gui --quiet --eval "pkg install matlab_compat/io-2.4.11.tar.gz"
- octave --no-gui --quiet --eval "pkg load io"
```

**Comment by coverney** [comment]
In regards to the Java problem, I think I figured it out. (It had something to do with the discrepancy between bitness.) Is there anything I need to change in the .travis.yml file to get the java objects to work in the build?

**Comment by coverney** [comment]
I am trying to connect my test_colormodel_excel with Travis, but I am having trouble with the Java support. The error is ```No Java support found (no Java JRE? no Java pkg installed AND loaded?)```. It works on Octave locally. I was wondering whether the 32 bit or 64 bit version of Octave is installed on Travis.

**Comment by coverney** [comment]
I tried a bunch of things. Both Java and Octave are 64 bit. But when I try to evaluate ```version('-java')```, I get ```no java available```. At this point, I am pretty stumped, but I will keep thinking about this problem as I tackle the other issues. Do you have any idea how to approach this problem?

**Comment by coverney** [comment]
Some resources I found: 
- https://octave.org/doc/interpreter/Making-Java-Classes-Available.html#Making-Java-Classes-Available
- https://github.com/travis-ci/travis-ci/issues/7253 (tried changing to Java JDK 9, but didn't fix the problem)

**Comment by jakebeal** [comment]
Looks like (in general) Octave can read .xlsx but not .xlsm.
https://wiki.octave.org/IO_package#About_read.2Fwrite_support

Can you save a "test copy" that throws away the .xlsm and is just .xlsx?

**Comment by coverney** [comment]
I could try that, but I was able to get Octave to read my .xlsm file with the io package.

**Comment by jakebeal** [comment]
Right: in that table, it shows the different interfaces, and since you're on windows, you have the COM interface as well as the OCT interface.  On other platforms, one only has the OCT interface unless you go through a lot of pain to figure out how to get the UNO interface---and it's listed as being unstable right now.

**Comment by coverney** [comment]
Sounds good. I will change the .xlsm file to .xlsx. Do you think we still need to connect a JRE to Travis to fix the no java available problem?

**Comment by jakebeal** [comment]
I don't think you'll need to worry about that any more --- and looking at Travis logs, it looks like we do have Java there, it's just that octave isn't set up to use it properly.  Using .xlsx, Octave should have no need for it, since we're not having any problem reading the bead .xlsx either

**Comment by coverney** [comment]
Great! I will test it out again with my next push of changes. Thank you very much!

**Comment by coverney** [comment]
I undid my changes from yesterday and changed my test template to .xlsx files, but I am still encountering the same problem.

**Comment by coverney** [comment]
Now I am getting this error: ```The command "sudo apt-get -y -qq update" failed```

**Comment by jakebeal** [comment]
That error sounds like an infrastructure failure, not a problem on your end.

**Comment by coverney** [comment]
Is there anything I can do about that?

**Comment by jakebeal** [comment]
I don't think so, other than restart the build and see if it works the second time --- I just restarted it, in fact, but it hasn't kicked off properly after 5 minutes, so 

I would advise to make sure everything's testing properly on your local machine, and we'll come back to Travis as a worry later.

**Comment by coverney** [comment]
Started test for color model and batch analysis.
