### ISSUE TITLE
Excel Comparison analysis remove "End Row Number"

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#302]
There should be a way to get rid of "End Row Number" in Excel comparison analysis.

**Comment by coverney** [comment]
This can be addressed by justing going through column A in the Comp Analysis sheet and going down until it finds a cell with content that matches with "Required: Instructions..." Two rows below that is the preference row

**Comment by coverney** [comment]
Done, changes in pull request #318
