### ISSUE TITLE
Excel remove path to TASBE install location

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#303]
TASBE is supposed to install such that we don't need a code directory location, since it should always be in Matlab's path.  If this isn't the case on Windows / via VBA from Excel, can we somehow fix this fact?

**Comment by coverney** [comment]
I can't seem to run any of the TASBE functions without the code directory or at least calling ```tasbe_set_path``` in the right location beforehand.

**Comment by jakebeal** [comment]
On Mac and Linux systems, running 'make install' launches Matlab and/or Octave with a command that runs `tasbe_set_path` and automatically includes the results into the path at startup.  There should be some Windows equivalent that can be done for install, though I don't know what it is.

**Comment by coverney** [comment]
I found this: https://www.mathworks.com/matlabcentral/fileexchange/1529-makeinstall

**Comment by jakebeal** [comment]
That made me realize: of course we can just tell somebody to run the command themselves from within Matlab!

The Manual installation is just to go to the TASBE directory in Matlab/Octave and run:
`tasbe_set_path(); savepath();`

Check if that works for you (and solves the Excel code path problem too). If so, let's just add that to the README as the recommended method of installing on Windows.

**Comment by coverney** [comment]
It seems to have worked!! I tried closing Matlab and it still worked. So basically we will just have everyone run those lines in Matlab before using the Run Button? Is it okay to only run it once?

**Comment by jakebeal** [comment]
We shouldn't have it be part of the Excel sheet at all --- we should just make the installation instructions clearer in the README.  I've just updated that to explicitly include Windows installation instructions.

Then in the Excel README, we should tell them to make sure they've installed TASBE and aren't just just running it from its directory.

**Comment by coverney** [comment]
Sounds good!

**Comment by coverney** [comment]
Done: modified the Excel README and deleted instances of the code directory from the spreadsheet and VB functions.

**Comment by coverney** [comment]
Can't be tested on Travis (no VBA connection) but works locally.
