### ISSUE TITLE
X00D_TRE-Flp-FF4T_x000D_LC41_x000D__x000D_48_x000D__x000D__x000D_

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#304]
Running `analyzeFromExcel` batch analysis on 'HT143_48hr_comparison.xlsm' from Matlab on a Mac, I got very strange plot names, like: `X00D_TRE-Flp-FF4T_x000D_LC41_x000D__x000D_48_x000D__x000D__x000D_-bincounts.png`

This is a shortened version, the original was apparently longer:

> Plotting histograms.Note: Name "HT143-B_x000D_TRE-Flp-FF4T_x000D_LC41_x000D_–_x000D_48_x000D__x000D__x000D_-bincounts" contains unsafe characters: abbreviated to "HT143-B_x000D_TRE-Flp-FF4T_x000D_LC41_x000D__x000D_48_x000D__x000D__x000D_-bincounts".

**Comment by coverney** [comment]
I did not have that problem when running the batch analysis. I will keep an eye out in case I see this bug again. What do you think may cause this?

**Comment by coverney** [comment]
According to the internet, the 'x00D' is the hexadecimal for the return character. I think I can find a way to trim that out.

**Comment by coverney** [comment]
You can manually remove line breaks in excel or should we just do a strrep for x000D whenever we extract names?

**Comment by jakebeal** [comment]
I think that we should do a general cleaning of the strings for problematic characters. x000D is clearly one, but there might be a more general set of such that need to be removed eventually.

**Comment by coverney** [comment]
What should we consider as problematic?

**Comment by jakebeal** [comment]
Let's start with just running a "trim" to get rid of leading and trailing whitespace, which should also deal with the returns.

**Comment by jakebeal** [comment]
Quite possible --- when I googled, I saw somebody having similar problems in PHP.

**Comment by coverney** [comment]
I also did some googling and saw that the presence of x000D is an established problem with Excel.

**Comment by coverney** [comment]
I added a sanitize string function in ```TemplateExtraction```: 
```
function new_value = sanitizeFromExcel(value)
            if isstring(value) || isa(value, 'char')
                new_value = strtrim(value);
            else
                new_value = value;
            end
        end
end
```
which gets called in ```getExcelValuePos```. I tried replicating the X000D error by adding white spaces to a few of the Excel cells, but I could not get X000D to appear. @jakebeal would you be able to test this out after I push my code?

**Comment by jakebeal** [comment]
Can do; push and I will test sometime tomorrow.

**Comment by coverney** [comment]
A test is written via batch analysis.
