### ISSUE TITLE
Allow 'comparative' as well as 'plusminus' for analysis type

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#305]
In `analyzeFromExcel`, the `plusminus` case should also accept keyword `comparative` (and similar), since we're migrating from `plusminus` to `comparative` in general

**Comment by coverney** [comment]
Done! Added ```comparative``` and some similar options.

**Comment by coverney** [comment]
Wrote test, changes in next pull request
