### ISSUE TITLE
Swap column and value in comparative group names

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#306]
I think it will be more natural and informative to write comparative group names as `Flp=Yes` rather than `Yes-Flp`.

**Comment by coverney** [comment]
Would we also be able to remove the stem name cells in plusminus and transfer curve analysis? The stem names can automatically be the values of the sample column names in comparison groups. If there are no comparison groups, then the stem name would be empty. On the other hand, the device name would default to the experiment name. I would then change the way the titles are generated in the plot functions such that it is device name = stem name.

**Comment by jakebeal** [comment]
If the stem name isn't really useful any more, we can either remove it or just leave it as an override that defaults as you suggest.

**Comment by coverney** [comment]
Sounds good!

**Comment by coverney** [comment]
Wrote test, changes in next pull request
