### ISSUE TITLE
colormodel not working

### ISSUE THREAD

**Issue by jhletendre** [TASBE/TASBEFlowAnalytics#308]
Currently testing updated code from coverney.excel. Colormodel has ceased to function in new and old workbooks (JHT6_New and JHT10), attaching a screenshot of error message. Unedited file can be found on resilio sync.
![colormodel_error](https://user-images.githubusercontent.com/30151391/43036812-836b21b2-8cd5-11e8-9a22-571252d9c49b.PNG)

**Comment by jakebeal** [comment]
Looks likely to be an issue with the relative file names, I would guess.  Can you check this out @coverney ?

**Comment by coverney** [comment]
This made me realize that I did not make the data stems in file templates relative to the template location. Should that be a feature? Also, I have a hunch that the answer lies with the contents of the template.

**Comment by jakebeal** [comment]
I think that all file locations should behave consistently with one another --- this is one to add a test for, I think, to make sure that all of the outputs are appearing where expected and with the names expected.

**Comment by jakebeal** [comment]
Note: this is done, and should be pulled in soon.

**Comment by coverney** [comment]
Done and tested.
