### ISSUE TITLE
Excel interface: file name stems with '\' need protection in fprintf/sprintf usage

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#310]
@jhletendre reports the following issues:

> I'm still running into the sprintf issues about the \U or \F or any \ followed by a letter not being a recognized character.
> I've been able to work around the file reading error by replacing all the \ with \\ in the stem file names in the Excel template - it's a bit hacky but it's the only way matlab will read in the files. 

This almost certainly indicates a problem with strings being used in fprintf/sprintf without protection to keep '\' from being interpreted as a special character.  It should be able to be fixed by automatically transforming '\' to '\\' where used in the excel interface.

**Comment by coverney** [comment]
I never encountered this issue even though I tested both forward and backward slashes. Where are the " coming from?

**Comment by coverney** [comment]
Found this online: https://www.mathworks.com/matlabcentral/answers/36928-how-can-i-introduce-a-after-sprintf

**Comment by jakebeal** [comment]
Check @jhletendre's Excel files in the JHT6, JHT10 and JHT11 folders --- I believe those were the ones that he was running when the bug surfaced.

**Comment by coverney** [comment]
I found the cause of the bug!! Basically, I wrote a util function that makes sure that backslashes are read properly, but I forgot to apply it to the data stems in the filename templates, which are the only cells that Justin needed to add the double backslashes.

**Comment by coverney** [comment]
Made a first attempt at fixing this. Will ask Justin to test.

**Comment by coverney** [comment]
Tested via color model.
