### ISSUE TITLE
Excel Interface: add TASBEConfig for histogramFiles

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#312]
Add an option to output the histogramFile.csv data in the Excel sheet in the Optional Settings tab, set default to 1. Potentially do the same thing for the statisticsFiles.

**Comment by jakebeal** [comment]
@jhletendre --- this should help with your questions

**Comment by coverney** [comment]
Done! Wrote test and passed. Changes in next pull request.

**Comment by jhletendre** [comment]
This sounds great, I'll let be going through everything new tomorrow as I'm analyzing this week's experiment and let you know how the new functionalities work.
