### ISSUE TITLE
Failure to read from Samples tab in Excel input template

### ISSUE THREAD

**Issue by jhletendre** [TASBE/TASBEFlowAnalytics#323]
Running the colormodel analysis using the latest excel input template (I'm not sure tbe version as it's not listed but latest as of 8/1/2018) yields the error found below. It seems like the code is failing to read the headers from the sample tab.

Error using TASBESession.error (line 122)
Error using TASBESession.error (line 122)Did not
find template # or exclude from batch analysis
columns in "Samples".Error in
TemplateExtraction/findSampleCols (line 349)
TASBESession.error('TemplateExtraction',
'MissingHeader', 'Did not find template # or
exclude from batch analysis columns in
"Samples".');Error in TemplateExtraction (line 107)
obj.coordinates = obj.findSampleCols();Error in
analyzeFromExcel (line 20)        extractor =
TemplateExtraction([path name ext]);

Error in analyzeFromExcel (line 52)
                TASBESession.error(id_parts{1},
                id_parts{2}, msg);

**Comment by coverney** [comment]
Fixed! Caused by a spelling error in "Exclude from Batch Analysis" cell.
