### ISSUE TITLE
Excel Spreadsheet video tour

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#332]
Make a video tour of how to use the Excel spreadsheet, including some key places where people are likely to run into confusion.

**Comment by coverney** [comment]
I am currently working on the video. What would be the best way to add it to GitHub? I could upload it to YouTube first.

**Comment by jakebeal** [comment]
Let's see how big it is --- if it's not too big, maybe the right thing to do is to create a website repo for the TASBE organization and to store it there (as well as working to make the website make sense).

**Comment by coverney** [comment]
I just exported the video. It is a 440.3MB large MP4 file.

**Comment by coverney** [comment]
Should I try adding it to the website repo?

**Comment by jakebeal** [comment]
I've now set up a new repository for hosting the website: https://github.com/TASBE/TASBE
Can you put it there?  Hopefully this should be an easy place to transfer things over to per: https://help.github.com/articles/user-organization-and-project-pages/

**Comment by coverney** [comment]
Sounds good. Do we also want to move over the old website?

**Comment by jakebeal** [comment]
Yes, I think that would be good.

**Comment by coverney** [comment]
I put the old gh-pages code into the new repo, but when I tried going to https://tasbe.github.io/, I received a "There isn't a GitHub Pages site here" message.

**Comment by coverney** [comment]
I think this may be due to the current existence of the gh-pages branch. Would I be able to delete it since I copied over all the information?

**Comment by coverney** [comment]
Also, the video is larger than the 100MB size limit, so I will upload it to YouTube and embed the YouTube video into the README. Found how to do that here: https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md

**Comment by coverney** [comment]
Link to video: https://youtu.be/EMQJlTAzuDU

**Comment by coverney** [comment]
Added to website (https://tasbe.github.io/TASBE/)
