### ISSUE TITLE
Option to input from CSV

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#344]
To support use from miscroscopy, microfluidics, etc., we should have the ability to import data from CSV rather than from FCS files.

This will include a need to interpret headers or else have header information explained to this. A good starting point would be to be able to consume our own point-cloud CSV outputs.

**Comment by coverney** [comment]
I am thinking of creating another version of ```fca_readfcs``` for csv files. Is there any example file that I can reference, or do I just try to read in the point cloud data even if the data is already in MEFL units?

**Comment by jakebeal** [comment]
I think writing fca_readcsv sounds like a good idea. :-)

For testing, maybe check out @tim-tx work upstream in https://github.com/tim-tx/microtaspy
@tim-tx: are there any particular files you'd recommend?

**Comment by tim-tx** [comment]
I have no csv files in that repository, but I can probably provide you with one. I already had a conversation with Katherine about sharing one publicly. Do you have any restrictions on the number events? For the data sets we've processed so far, the count is usually rather low, <1000.

**Comment by coverney** [comment]
No restrictions come to mind. I am excited to test out your csv files.

**Comment by coverney** [comment]
I took a closer look at the CSV files that Tim sent me. I understand their structure with the columns consisting of varying intensity and location measurements for three different channels and two different illuminations. Actually writing in the data from the CSV file is relatively straightforward, but I am not sure how to connect the CSV files to data read from FCS files since they have different parameters. Also, the CSV files do not have a HEADER or all the detector voltage, excitation power... parameters. I was wondering how I should go about arranging the read in data in a useful way.

**Comment by jakebeal** [comment]
I would suggest that as a first pass, that each column in the CSV simply be turned into a channel, and you generate a header that sets what can be set, leaving the rest blank (just as it might be for an FCS file that left values blank).  The two illuminations are like two similar filters, e.g., "strong green" and "weak green" could be like "mCherry-A" and "Texas-Red-A".  The locations are a non-illumination channel just like time is in a typical FCS file.

Looking at header fields read by fca_readfcs:
* fcstype: can be set to a new value of our own
* filename, filepath: set from file
* TotalEvents: number of rows
* NumOfPar: number of columns
* par: channel structs --- create leaving everything but name blank
* Creator, starttime, stoptime, timestep, cytometry, date, byteorder, datatype, system, project, experiment, cells, creator: leave blank

**Comment by coverney** [comment]
That makes much more sense! Thank you for the explanation.

**Comment by coverney** [comment]
I wrote a tentative ```fca_readcsv``` function and would like to discuss ways to test it during our next meeting before pushing any changes.

**Comment by coverney** [comment]
The tests for the pull request finally passed! I also created more detailed issues in regards to the next steps.
