### ISSUE TITLE
Excel: put outputs into a results sheet

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#356]
@jhletendre has been compiling TASBE outputs into an additional results sheet in his Excel templates. It seems that we ought to be able to do this automatically for most of the key outputs.

**Comment by coverney** [comment]
I did some brainstorming and come up with the following ideas/ questions that would be useful to discuss:
-  I think we should definitely output the count, gmeans, and stdev stats from ```statisticsFile``` after batch analysis. 
- I am thinking of organizing the results by listing out the experimental conditions/ samples names (with each sample making up a single row) and then the stats (similar to how Justin is organizing it right now)
- I was wondering if it makes sense if we put the results in a separate sheet right behind the corresponding template sheet. 
- Which plusminus results should I output? Justin currently only outputs InputSNR and OutputSNR.
- Should we deal with any of the results from transfer curve analysis? If so, which ones?
