### ISSUE TITLE
Warn when fraction of gated particles changes significantly

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#359]
We already warn when the fraction of gated particles is too low. We should also do cross-sample analysis to warn when some samples have a fraction of gated particles that is very different from others.  

Perhaps look at the median fraction gated, then warn for every sample more than a certain percent above or below that level? (Probably default to 10% variation).

**Comment by coverney** [comment]
Where is the warning that the fraction of gated particles is too low? I thought that it would be part of `flow.gateDiscardsWarning`, but that config is not used. Also, `fraction_kept` does not seem to be used outside of `GMMGating` and isn't part of any warnings.

**Comment by jakebeal** [comment]
`flow.gateDiscardsWarning` is the shared default for 'flow.preGateDiscardsWarning' and 'flow.postGateDiscardsWarning', which are used in reading files, resulting in an `n_removed` secondary output.

A good place for checking for sample-to-sample gating variation is at the bottom of `per_color_constitutive_analysis.m`, where we already have checks for variation in number of events.

**Comment by coverney** [comment]
What would be a good test for this?

**Comment by coverney** [comment]
I am thinking of making `conditionFracGatedWarning` (the TASBE Config I added) really small like 0.01 and checking to make sure the warning happens.

**Comment by jakebeal** [comment]
Yes, that sounds like a good test --- make it small enough that normal random variation will be enough to make it fail.

**Comment by jakebeal** [comment]
Fixed by #456
