### ISSUE TITLE
Automatically sense detector saturation

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#360]
When the detector is saturated high, we end up with a sudden peak at the top of its range, followed by nothing (or almost nothing).  It would be nice to be able to give warnings for saturation on samples.

**Comment by coverney** [comment]
Where would be a good starting point to delve into this issue? I looked into the `rangeMax` TASBE configs, but I am not sure if that is the correct range regarding detector saturation.

**Comment by jakebeal** [comment]
This is something that's going to be detected by looking at the histograms of a sample, so compute_sample_statistics might be the place to go.

**Comment by jakebeal** [comment]
Suggested heuristic: 
- Is there any Bin i such that:
- count(i-2) has count < [ConfigThreshold: default=0.1] * count(i)
- count(i+2:end) are all 0

**Comment by coverney** [comment]
Where would be a good place to test this? Also, do we have any fcs files with detector saturation?

**Comment by jakebeal** [comment]
Probably also in test_batch_analysis.  I think we've got at least some detector saturation in test files, but am not sure; I can check.  If we don't, I've got others.

**Comment by jakebeal** [comment]
The `SSC-A` and `SSC-H` channels of `example_controls/171221_E1_p1_AJ02.fcs` both have saturations.  It would be good to have the test look at these and several others channels (the SSC ones would be uncalibrated, of course), to make sure it finds precisely those two and no others.

**Comment by coverney** [comment]
Sounds good! Thank you! I will try to do that in the near future.

**Comment by coverney** [comment]
I added the saturation detection in `subpopulation_statistics` and tried testing it with `example_controls/171221_E1_p1_AJ02.fcs` by varying data column, `selector`, (which should correspond to the different channels). Using the algorithm we talked about, I was not able to get detector saturation for `SSC-A` and `SSC-H`. I was wondering if I should modify the algorithm to get those to work. The results for `SSC-A` are:
           0
           0
           0
           0
           0
           0
           0
           0
           0
          15
          66
         107
         122
         137
         190
         282
       22219
       53058
        6510
        2126
        2145
           0 till the end

And the results for `SSC-H` are:
           0
           0
           0
           0
           0
           0
           0
           0
           0
           0
          76
          99
         128
         135
         187
         280
       22712
       53738
        6606
        2534
         483
           0 till the end

I will continue working on this on Tuesday morning. I hope you have a great weekend!

**Comment by coverney** [comment]
I got the results by calling:
`subpopulation_statistics(bins, data, 3, 'geometric')`
and 
`subpopulation_statistics(bins, data, 9, 'geometric')`

**Comment by jakebeal** [comment]
Looks like I was only seeing the effects because I was running with a finer granularity in my bins. If you change from the default 0.1 width bins to 0.02 width bins, then you'll get a saturation peak in channel 3 (but not 9, which we can drop).

**Comment by coverney** [comment]
I changed the bin size but I still didn't get the warning for channel 3 (it is super close). The results are:
         342
         290
         266
        1879
           0
           0
           0
           0

290 > 187.9. I get the warning if I change the bin width to 0.01. Should I just do that?

**Comment by jakebeal** [comment]
Sure: either change the width to 0.01 or (better yet) set the threshold config from 0.1 to 0.2 for purposes of the test.

**Comment by coverney** [comment]
I changed the config, and now I am getting the warning for channels 2, 3, 4, 5, 7, and 8.

**Comment by jakebeal** [comment]
Is that right or wrong given the histograms on the other channels?

**Comment by coverney** [comment]
For channel 2, it gives the warning because there is a zero two places before the final value. I can add a check to make sure channel(i-2) is not zero

**Comment by coverney** [comment]
In general, if there were any 0 values before the sudden peak, can there still be detector saturation? Also, should the peak before the long trail of 0s be the highest peak?

**Comment by coverney** [comment]
If I add these additional tests, then only channel 3 would have a saturation warning.

**Comment by jakebeal** [comment]
It sounds like in general the heuristic is being too sensitive to noise when there are small values.

My thought would be: 1) the comparison should be not against i-2 but against an average over a few nearby ones (e.g., i-4:i-2), and 2) it should also have a minimum valid count on the bin count of the peak (e.g., defaulting to 100, like in AnalysisParameters)

**Comment by coverney** [comment]
Sounds good. I will make those changes and re-run the tests

**Comment by jakebeal** [comment]
Fixed by #457.
