### ISSUE TITLE
Need to fix channel equality testing when laser/filter values are set identically for two different channels

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#361]
We noticed that TASBE was generating identical Geo Mean and Geo STD values for two different channels (FSC and SSC) even though the raw values from fcs files are actually different for these two channels.  Below is the configuration for both:

         {
            "_comment1": "name must exactly match the channel name in the FCS files",
            "name": "FSC - Area",
            "_comment2": "excitation is the channel laser; these examples show the recommended values",
            "excitation_wavelength": 488,
            "_comment3": "emission_filter is the channel optical filter; these examples show the recommended values",
            "emission_filter": {
                "type": "bandpass",
                "center": 488,
                "width": 10
            },
            "_comment4": "emission_filter can also be of type 'longpass', which has cutoff instead of center and width"
        }, {
            "_comment1": "name must exactly match the channel name in the FCS files",
            "name": "SSC - Area",
            "_comment2": "excitation is the channel laser; these examples show the recommended values",
            "excitation_wavelength": 488,
            "_comment3": "emission_filter is the channel optical filter; these examples show the recommended values",
            "emission_filter": {
                "type": "bandpass",
                "center": 488,
                "width": 10
            },

**Comment by jakebeal** [comment]
Background: this is a feature that has become a bug, since we added unprocessed channels and started working with FSC and SSC.

It was a feature when it let us find equality between "PE-Texas Red-A" and "PE-Tx-Red-YG-A" despite their different names.  It's now a bug because FSC and SSC typically have the same laser/filter combination, but are not equal.
