### ISSUE TITLE
Need to use better X-axis label for count plots

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#362]
TASBE currently uses "MEFL" on the X-axis even though they have multiple different units being plotted together.

**Comment by jakebeal** [comment]
Specifically, this happens on "batch analysis" plots that put multiple colors on one X axis, but a color model is being used that is either only partially resolved (some channels a.u.) or includes size beads

It may also happen in plus/minus plots that show both input and output on the same axis.

**Comment by jakebeal** [comment]
Also related to #140
