### ISSUE TITLE
Need to fix plot_batch_histograms for single channel

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#364]
Prior to invoking this function, we have used the setLineSpec function to specify line colors.  For multi-channel cases, the function can then be invoked without the last colorspecs argument, it will rely on earlier setLineSpec calls to get the corresponding colors.  This is not the case for a single channel case, whereas we will get an "error: Size of linespecs does not match with number of channels" message if  colorspecs is not provided.  As a result, I had to use the following conditional code to deal with the two scenarios:

 55     longnames = self.octave.pull('channel_long_names')
 56     print("longnames: {} type: {}".format(longnames, type(longnames)))
 57     if type(longnames) == oct2py.io.Cell: longnames = longnames.tolist()
 58     if type(longnames[0]) == list: longnames = longnames[0]
 59     print("longnames: {} len: {}".format(longnames, len(longnames)))
 60     if (len(longnames) == 1):
 61       colorspecs = []
 62       colorspecs.append(wavelength_to_rgb([x['emission_filter']['center'] for x in self.cytometer_config['channels'] if x['name'] == longnames[0]][0]))
 63       colorspecs = '{' + ','.join(colorspecs) + '}'
 64       print("colorspecs: {}".format(colorspecs))
 65       self.octave.eval('plot_batch_histograms(results, sample_results, cm, {});'.format(colorspecs))
 66     else:
 67       self.octave.eval('plot_batch_histograms(results, sample_results, cm);')

When presented with a three channel scenario, here is what I got in the printout:
longnames: [[u'YFP - Area' u'FSC - Area' u'SSC - Area']] type: <class 'oct2py.io.Cell'>
longnames: [u'YFP - Area', u'FSC - Area', u'SSC - Area'] len: 3
Plotting histogramswarning: axis: omitting non-positive data in log plot

For a single channel scenario:
longnames: [u'BL1-A'] type: <class 'oct2py.io.Cell'>
longnames: [u'BL1-A'] len: 1
colorspecs: {[0.36706718774955405, 1.0, 0.0]}
Plotting histogramswarning: axis: omitting non-positive data in log plot

and the color specified earlier via setLineSpec will be overridden by colorspecs.

**Comment by jakebeal** [comment]
Looks like we had a bad initialization that created an array of `{1 N}` rather than a 1xN array. For N>=2, the junk values were overwritten, but at N=1 the bug was exposed.  Fix committed and verifying now.
