### ISSUE TITLE
Colormodel: Not reading FSC file for MEFL conversion

### ISSUE THREAD

**Issue by jhletendre** [TASBE/TASBEFlowAnalytics#366]
Trying the new size calibration tool, I'm trying to calibrate my FSC channel to MEFL but the file seems to not be read properly? The code and .fcs files are on resilio sync under JHT26. Not 100% sure what's happening, this is the error message I receive from running the colormodel.m script:

Undefined function 'isUnprocessed' for input arguments of type 'char'.

Error in ColorModel (line 76)
                    if(~isUnprocessed(channels{i}))

Error in JHT26_colormodel (line 68)
CM = ColorModel(stemColorBeads, stemBlank, channels, colorfiles, colorpairfiles,sizebeadfile);

**Comment by coverney** [comment]
That is interesting. I will try to take a look at it as soon as possible.

**Comment by jakebeal** [comment]
Based on conversation with Justin yesterday, I believe this issue is now resolved.
