### ISSUE TITLE
Fix TemplateExtraction such that row numbers are not harcoded

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#367]
The parameters in "Calibration" should not have hardcoded row numbers. Instead, write a function in ```TemplateExtraction``` that finds the row numbers based on section header names. I thought of this bug after making some significant changes by adding the size beads feature. Hopefully, this will allow users to continue to run their old batch templates without having to add in the size bead sections.

**Comment by jakebeal** [comment]
Fixed by #379
