### ISSUE TITLE
Log plots on fold activation

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#39]
Enable option to plot fold activation as log rather than linear.

**Comment by jakebeal** [comment]
Fixed in 49d4084

**Comment by jakebeal** [comment]
Now that I've got unit testing set up, there will be regular movements from "develop" to "master" with each new release: "master" represents a promise that regression testing says I didn't break anything.

This fix, for example, has just gone into  [Release 1.2.0-beta](https://github.com/TASBE/TASBEFlowAnalytics/releases/tag/1.2.0-beta).  I plan to be releasing patches often, and every major bug fix will be in a release, so except in unusual circumstances you can probably just stay tracking master.
