### ISSUE TITLE
Emit JSON header for point cloud files

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#397]
For a collection of point cloud files it would be useful to have machine-readable information about what exactly their columns mean, and how they relate to color channels.

Let us do this by emitting a JSON file as a header.  This header can be shared by all of the point cloud files produced from a batch, because they all use the same color model and same analysis parameters.

**Comment by coverney** [comment]
I was able to generate and save a json header file for the point cloud files, but as I was thinking about the best place to read back in the json file, I thought of the following question:
- Why should we have a json header file when the point cloud csv files already have a header row with the channel names? I could also look into transcribing additional header information from the original fcs header.

**Comment by coverney** [comment]
Currently, I am saving the channel names in the json file instead of the print names since the original fcshdr has channel names.

**Comment by jakebeal** [comment]
You can save both if you want: no shortage of space in the JSON!

**Comment by coverney** [comment]
Good news: I was able to read back in the point cloud files and successfully rerun batch analysis. I compared the point cloud files and graphs and they were identical! Next, I think I will work on issue #398 and then start the datafile object refactoring. Do you think I should push anytime before finishing all of the refactorings? In order to get the point cloud files to work, I had to change a few functions (i.e. ```readfcs_compensated_ERF``` and ```readfcs_compensated_au```).

**Comment by jakebeal** [comment]
If you've got tests that validate everything's still working through the refactoring, I'm in favor of integrating early and often.  That reduces the chance of me accidentally introducing a conflict through a parallel separate change.

**Comment by coverney** [comment]
I will create some tests and push something before the major refactoring

**Comment by coverney** [comment]
The tests for the pull request finally passed!
