### ISSUE TITLE
Add file path information to CSV JSON header

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#398]
It would be good to include in the CSV JSON header what are the files that it has been generated for.

The paths in some situations would want to be relative, and in others absolute.  That should be a config option, probably defaulting to absolute.

This could be used for a warning if you're applying the header the something it's not generated for.

**Comment by coverney** [comment]
I think I can find a way to add the filenames to the JSON, but currently, I am not using that feature when I read in the CSV files. (I would probably use it for an extra warning check.) Also, should the parameter that determines whether the filenames are relative or absolute be in TASBEConfig?

**Comment by jakebeal** [comment]
Sounds good.

As for where the relative/absolute parameter goes... it should only be used on writing out, not reading in (for reading in, you don't have a choice about what type of pathname is in the file: it just is what it is).  Thus, I think it can go in TASBEConfig right alongside the parameter that decides whether to write the CSV files at all.

**Comment by coverney** [comment]
Just implemented this feature and got it working. Now, I just need to clean some things up and write tests before creating a pull request.

**Comment by coverney** [comment]
I just created a pull request in the tutorial to add in the point cloud files so I can reference them while testing reads csv.

**Comment by coverney** [comment]
While trying to get the tests to pass I encountered two problems:
1. there seems to be an error from ```stem_name = TASBEConfig.get('OutputSettings.StemName');``` within the ```writePointCloudHeader``` and I am not sure why that is
2. octave does not support the functions that I used to read in the csv file, so I am in the midst of making it Octave compatible.

**Comment by coverney** [comment]
The tests for the pull request finally passed!
