### ISSUE TITLE
Also allow color model to be generated from CSV rather than FCS data

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#399]
When the JSON / CSV reader is complete, we should also figure out a way for it to apply to building the color model.

**Comment by jakebeal** [comment]
Might already be working, but needs testing.

**Comment by coverney** [comment]
try this out after refactoring (#411)

**Comment by coverney** [comment]
I think this is working? We just need to test it. What files should we use for that?

**Comment by jakebeal** [comment]
The same ones, just converted to CSV?

**Comment by coverney** [comment]
So we would use the fcs read function to read the fcs files and then make csv files from the data? Or is there a more straightforward way to convert fcs into csv?

**Comment by jakebeal** [comment]
Not as part of the test, but yes, just like you created the other CSVs for other tests.

**Comment by jakebeal** [comment]
Testing is now accomplished via #446
