### ISSUE TITLE
Remove the defaultCSVReadHeader config and implement datafile objects

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#411]

**Comment by coverney** [comment]
I was wondering whether we should have the users input the JSON header name each time they want to create a DataFile object with a csv type and error if they don't include it.

**Comment by coverney** [comment]
I am thinking of creating a @DataFile folder with setter and getters for the following properties:
- type (fcs or csv)
- header name (required for csv type)
- filename 

I will also include the fca_read functions in the @DataFile folder. Does that seem reasonable?

**Comment by jakebeal** [comment]
Both of these sound reasonable.

If you want to be fancy, you can also have a "CSV data file factory" pattern that would take a JSON file and then have a method to create datafile objects from just the name, automatically associating the JSON file in the factory (and possibly validating as well).

**Comment by coverney** [comment]
Should we create DataFile objects for all of the files needed to generate the colormodel as well?

**Comment by jakebeal** [comment]
I think that anywhere that we currently use a string to identify a file, we should be able to accept a DataFile object.

**Comment by coverney** [comment]
I refactored everything and the tests worked locally, but there is still some problems with the ```getExcelFilename``` function in Travis.

**Comment by jakebeal** [comment]
Is this now closed by #424?
