### ISSUE TITLE
Undefined function 'resolve' for input arguments of type 'ColorModel'

### ISSUE THREAD

**Issue by jhletendre** [TASBE/TASBEFlowAnalytics#417]
Matlab fails to execute ColorModel analysis after displaying the following messages:
"Gating autodetect using NN.NN% valid and non-saturated data"
"Computing individual components.."
"Undefined function 'resolve' for input arguments of type 'ColorModel'"

ColorModel scripts were previously working (as of ~2 months ago), and updating code via GitHub desktop does not help.

**Comment by jakebeal** [comment]
The ColorModel resolve function is definitely working, both in the continuous integration and when I tested with 7.6 just now.  This sounds like your checkout of TASBE might have gotten into a broken state again somehow (e.g., via a conflicting git merge).

Can you try deleting TASBE making a new clean check-out?

**Comment by jhletendre** [comment]
That's actually the first thing I tried with no fix - trying to close matlab and restart my computer now to see if that helps

**Comment by jakebeal** [comment]
Stale state in Matlab can also cause this, if you have conflicting class definitions loaded.

**Comment by jakebeal** [comment]
Were you able to clear this up after our discussion today?

**Comment by jhletendre** [comment]
Yes, thank you very much - just deleted all instances of TASBE and re-cloned. Everything is running fine and no more duplicate/missing files.

**Comment by jakebeal** [comment]
Excellent! I will close this issue as resolved now.
