### ISSUE TITLE
Received unexpected "structure has no member 'voltage'" error message

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#420]
When testing TASBE 7.6.1's capability of reading CSV files containing flow events as input, I encountered the following error message.  It is unclear what triggered this error.   Please email gzheng@netrias.com if you need more information.

Traceback (most recent call last):
  File "/src/fcs.py", line 129, in <module>
    main(args)
  File "/src/fcs.py", line 101, in main
    experiment_analysis.analyze()
  File "/src/analysis.py", line 49, in analyze
    self.octave.eval('[results sample_results] = per_color_constitutive_analysis(cm,file_pairs,channel_names,ap);')
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 484, in eval
    plot_res=plot_res)
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 369, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 568, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: structure has no member 'voltage'
error: called from:
    confirm_channel at line 19, column 1
    readfcs_compensated_au at line 30, column 16
    readfcs_compensated_ERF at line 16, column 33
    read_data at line 27, column 33
    per_color_constitutive_analysis at line 30, column 27

**Comment by jakebeal** [comment]
Can you please post your source JSON (headers at least) and the top few lines of a reference CSV?

**Comment by georgebzheng** [comment]
Header file in JSON:
{           
    "channels": [
        {   
            "name": "Time",
            "print_name": "Time",
            "unit": "a.u."
        },  
        {   
            "name": "FSC-A",
            "print_name": "FSC - Area",
            "unit": "a.u."
        },  
        {   
            "name": "SSC-A",
            "print_name": "SSC - Area",
            "unit": "a.u."
        },  
        {   
            "name": "BL1-A",
            "print_name": "BL1 - Area",
            "unit": "a.u."
        },  
        {   
            "name": "RL1-A",
            "print_name": "RL1 - Area",
            "unit": "a.u."
        },  
        {   
            "name": "FSC-H",
            "print_name": "FSC - Height",
            "unit": "a.u."
        },  
        {   
            "name": "SSC-H",
            "print_name": "SSC - Height",
            "unit": "a.u."
        },  
        {   
            "name": "BL1-H",
            "print_name": "BL1 - Height",
            "unit": "a.u."
        },  
        {   
            "name": "RL1-H",
            "print_name": "RL1 - Height",
            "unit": "a.u."
        },
        {
            "name": "FSC-W",
            "print_name": "FSC - Width",
            "unit": "a.u."
        },
        {   
            "name": "SSC-W",
            "print_name": "SSC - Width",
            "unit": "a.u."
        },
        {   
            "name": "BL1-W",
            "print_name": "BL1 - Width",
            "unit": "a.u."
        },  
        {   
            "name": "RL1-W",
            "print_name": "RL1 - Width",
            "unit": "a.u."
        },  
        {   
            "name": "live",
            "print_name": "live",
            "unit": "a.u."
        }   
    ],      
    "filenames": [
        "sample.transcriptic.aq1c667guaaxnz.csv",
        "sample.transcriptic.aq1c667gubkj75.csv",
        "sample.transcriptic.aq1c667gu97umy.csv",
        "sample.transcriptic.aq1c667guaq2rc.csv",
        "sample.transcriptic.aq1c667gu9rc4f.csv",
        "sample.transcriptic.aq1c667gu94jbv.csv",
        "sample.transcriptic.aq1c667gu8frka.csv"
    ]       
} 

Top few lines of a reference CSV:

Time,FSC-A,SSC-A,BL1-A,RL1-A,FSC-H,SSC-H,BL1-H,RL1-H,FSC-W,SSC-W,BL1-W,RL1-W,live
0.0,1048575.0,1048575.0,89224.0,297319.0,142597.0,1048575.0,647.0,6982.0,1023.0,1023.0,0.0,0.0,0
1.0,57472.0,264568.0,-20.0,53.0,46161.0,208877.0,44.0,81.0,39.0,71.0,0.0,0.0,1
1.0,49744.0,257848.0,3.0,90.0,38228.0,210887.0,68.0,167.0,39.0,68.0,0.0,0.0,1
1.0,33580.0,187912.0,23.0,119.0,30592.0,172870.0,51.0,85.0,29.0,49.0,0.0,0.0,1
2.0,49341.0,187646.0,-8.0,64.0,40498.0,156780.0,41.0,81.0,37.0,52.0,0.0,0.0,1
2.0,35196.0,144441.0,-67.0,111.0,31633.0,133937.0,25.0,92.0,30.0,45.0,0.0,0.0,1
3.0,41215.0,151903.0,16.0,-68.0,37151.0,136773.0,35.0,30.0,32.0,47.0,0.0,0.0,1
3.0,20129.0,87650.0,-69.0,23.0,19261.0,85062.0,23.0,41.0,22.0,38.0,0.0,0.0,1
5.0,36384.0,141725.0,59.0,153.0,30948.0,124655.0,71.0,63.0,31.0,47.0,0.0,0.0,1
5.0,34061.0,170510.0,100.0,32.0,29785.0,144394.0,48.0,91.0,31.0,50.0,0.0,0.0,1
6.0,152217.0,640042.0,80.0,169.0,47964.0,189088.0,76.0,91.0,108.0,191.0,0.0,0.0,1
6.0,29434.0,134779.0,93.0,6.0,26752.0,124973.0,54.0,44.0,27.0,44.0,0.0,0.0,1
6.0,32841.0,171273.0,19.0,-49.0,28836.0,154764.0,47.0,46.0,30.0,48.0,0.0,0.0,1
6.0,137195.0,722385.0,-13.0,99.0,89697.0,490809.0,75.0,144.0,53.0,162.0,0.0,0.0,1
6.0,68153.0,399882.0,69.0,83.0,37309.0,291997.0,113.0,152.0,50.0,99.0,0.0,0.0,1
6.0,30351.0,167279.0,10.0,-30.0,27740.0,157725.0,52.0,46.0,30.0,46.0,0.0,0.0,1

**Comment by jakebeal** [comment]
I've now been able to reproduce this issue: it looks like it's coming from an issue in a.u. vs. MEFL channel handling.
