### ISSUE TITLE
Excel Interface: (Minor) Displaying 'Batch Analysis Complete' immediately after clicking the run button

### ISSUE THREAD

**Issue by jhletendre** [TASBE/TASBEFlowAnalytics#421]

**Comment by jakebeal** [comment]
Can you please provide version information to make sure this hasn't already been addressed elsewhere?

**Comment by jhletendre** [comment]
Yes - using TASBE release 7.7.0 alpha, I think this is the most recent available through Github

**Comment by coverney** [comment]
I can't seem to replicate this issue, but I will do some more testing with the run buttons.
