### ISSUE TITLE
Bug in line 41 of code/writeFcsPointCloudCSV.m in TASBE 7.6.1

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#422]
Received error about negative index from line 41 of code/writeFcsPointCloudCSV.m.  This error would happen when the file name has fewer than 10 characters.  Before comparing the last ten characters of the file name against '_PointCloud', a length check on the name itself should be performed first.

**Comment by jakebeal** [comment]
@coverney This looks like it should be an easy fix.

**Comment by jakebeal** [comment]
@coverney I took over this issue as it's caused @georgebzheng to have to regress his TASBE version, and am about to submit a pull.
