### ISSUE TITLE
fca_read shouldn't be in library

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#425]
the library directory is for files that we didn't originate. fca_read and fca_readcsv should be in code/ rather than library.  Fixing this should be as easy as just moving the files.

**Comment by coverney** [comment]
should they be in code or @DataFile?

**Comment by coverney** [comment]
currently, fca_read is in DataFile

**Comment by jakebeal** [comment]
Looks like this is moot for fca_read, but fca_readcsv can still mode from library/ to code/
