### ISSUE TITLE
Use canonical (unix-style) pathnames in CSV header filename matching

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#426]
Right now, `fca_readcsv.m` deals with Mac/unix vs. Windows paths by stripping out all path identifiers:

```
    file_match = 0;
    filename_to_compare = strrep(strrep(filename, '/', ''), '\', '');

```

This can cause silent problems through false positive matches in unusual cases, e.g., `foobar/baz.csv` vs. `foo/barbaz.csv`.

A better way to deal with this is to convert pathnames to the canonical (unix) version, as Matlab can read in that form on Windows as well.  Examples of how to deal are here: https://www.mathworks.com/matlabcentral/answers/117110-dealing-with-and-windows-vs-unix-for-path-definition

**Comment by coverney** [comment]
Just to double check: it seems like we should replace all '\' with '/'

**Comment by jakebeal** [comment]
Yes, I believe that should work.
