### ISSUE TITLE
Excel sheet needs update for new TASBEConfig properties

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#444]
I've recently made a bunch of updates to TASBEConfig, putting things in there that were previously in the ColorModel, AGP, or nowhere.  Before the 8.0 release, we need to update the tutorial Excel sheet to match.

**Comment by coverney** [comment]
Should I continue to leave out the plot path configs?

**Comment by jakebeal** [comment]
That's fine.  None of the sense of things needs to change, just its locations.
