### ISSUE TITLE
CSV reading doesn't handle subset names

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#467]
Sometimes the name of a channel is a subset of the name of another channel. When this happens, CSV reading throws an error since it thinks the channel is duplicated.

**Comment by jakebeal** [comment]
I just committed a test change that exercises this issue, and am reassigning it over to you, since I think you'll have a chance to fix it before I do.

**Comment by coverney** [comment]
If the print name is FSC, then which column index should it record, FSC-A, FSC-H, or FSC-W? Also the print names in colormodel_csv.json don't match up with the `VarNames` in the actual csv (i.e. EYFP). Should we change the csv or use the name attribute from the json?

**Comment by coverney** [comment]
Nevermind my second question. It is answered by issue #466.

**Comment by coverney** [comment]
Also nevermind my first question. I think I understand the issues now.

**Comment by jakebeal** [comment]
If there is an exact match, like with FSC-A, then it shouldn't worry about
the subsetting

Thanks,
-Jake
(sent from my phone)

**Comment by coverney** [comment]
I am trying to incorporate the process of elimination search technique, and I just want to confirm that no 2 channels can be matched with the same CSV header. I am planning to search through all the channels and eliminate the CSV headers that have a perfect match with one of the channel names.

**Comment by jakebeal** [comment]
Agreed: the channels should be a 1:1 subset of CSV headers.

**Comment by jakebeal** [comment]
Fixed by #468
