### ISSUE TITLE
Detect and warn on duplicate condition IDs

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#469]
Any analysis run should never have duplicate condition IDs, as those conditions will then be indistinguishable.  Duplicate condition IDs should thus be a failing condition.

Among the effects of such an error is that the duplicate conditions' outputs will overwrite each other.

TASBE should thus detect and warn if there are duplicate IDs, so that the user can fix this condition.  We may also wish this to be an error condition, interrupting processing, and thus I think there should be a TASBEConfig for determining whether it's a warn or error.

**Comment by jakebeal** [comment]
The IDs should be checked both directly and against their safe-file-name transformed versions (e.g., "1-2" should match "1_2")

**Comment by coverney** [comment]
It seems like batch analysis and plusminus analysis both make sure that all files are present, but transfer curve doesn't. How do condition IDs work for transfer curve since the experiment name does not contain the condition id?

**Comment by coverney** [comment]
Update: I added this check for batch and wrote a test. For plusminus should we compare condition ids based on 
`experiment_name = [condition_name ': ' inducer_name ' ' batch_description{i}{3}{j}];` ?

**Comment by jakebeal** [comment]
For plus-minus, that sounds correct.
For transfer curve, we should check that none of the levels are the same (e.g., you shouldn't have value "10" twice)
