### ISSUE TITLE
Issue 407 branch on Tutorial?

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#476]
There is a stale un-merged branch on TASBE tutorial that claims to be for issue #407: 
https://github.com/TASBE/TASBEFlowAnalytics-Tutorial/tree/coverney.issue407

Does it have materials that need to be incorporated, or should it be discarded? If the former, it will take careful work, since it's the Excel file that was changed.

**Comment by coverney** [comment]
I think we can delete the branch. I referenced issue #407, and the Min valid a.u. cells are already in the current excel template on master.

**Comment by jakebeal** [comment]
Done.
