### ISSUE TITLE
Need to add SpheroTech URCP-38-2K lot AL02 to BeadCatalog

### ISSUE THREAD

**Issue by kevinwkeating** [TASBE/TASBEFlowAnalytics#497]

**Comment by jakebeal** [comment]
SpheroTech doesn't have AL02 listed on their templates page --- do you have access to a copy of the calibration sheet that came with the AL02 bottle?  If you can share a scan of it, we can add it to the catalog.

**Comment by jakebeal** [comment]
Thank you! Looks like this lot is identical to AJ02 and AJ03, so I've added it in with them.
The new sheet is included with patch release 8.3.1: https://github.com/TASBE/TASBEFlowAnalytics/releases/tag/8.3.1

Please confirm that this works for you, and we can close this issue.

**Comment by jakebeal** [comment]
@kevinwkeating Does this address the issue that you had?

**Comment by jakebeal** [comment]
I am going to close this issue on the assumption that this is now working; please comment and reopen if this is not the case.
