### ISSUE TITLE
Implement non-numeric tuning parameters, such as strings

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#53]

**Comment by jakebeal** [comment]
Can you please explain more what you are thinking about for this issue?

**Comment by bhwein** [comment]
I'm not sure what I was really thinking about this. I think I was thinking more on the lines of issue #55 that I posted. Basically where a device has many input conditions rather than a simple +/-, but not necessarily a dose response.

**Comment by jakebeal** [comment]
For now, then, I'm going to close this as duplicate of #55. Please feel free to add additional information or re-open if additional distinctions arise.
