### ISSUE TITLE
Error using plusminus.m script

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#64]
I'm getting these errors when I attempt to run the plusminus.m script. Any ideas what this means?

Error using legend>check_pv_args (line 598)
Unknown property: Minus.

Error in legend>make_legend (line 343)
check_pv_args(propargs);

Error in legend (line 294)
    make_legend(ha,args(arg:end),version);

Error in plot_plusminus_comparison (line 103)
legend(pmlegendentries,'Minus','Location','Best');

Error in analyze_plusminus2 (line 77)
    plot_plusminus_comparison(results{i},OS)

**Comment by bhwein** [comment]
This is happening on both a new experiment I have tried to put in and an old one. Also, it would be nice to know if there were changes in the template scripts (e.g. autodetect_gating ---> GMMGating)

**Comment by jakebeal** [comment]
Fixed in 28d23c90
