### ISSUE TITLE
sanitize underscores in figure titles

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#71]
Matlab interprets underscores as LaTeX, leading to silly-looking titles when there are underscores in, e.g., filenames.  This should be sanitized away.

**Comment by jakebeal** [comment]
Related to #140

**Comment by lisatiberio** [comment]
I have sanitized the files I have created.  To speed the process along, is there something specific I can search on?  Is title good enough or should I also search for xlabel, figure, plot, etc?

**Comment by jakebeal** [comment]
There are actually three distinct cases of sanitization, each of which should have its own "cleaning" function:
- Cleaning a file name ('sanitize_name' function, which should probably be renamed 'sanitize_filename')
- Cleaning a name for LaTeX representation ('clean_for_latex' function, which should be used for any _automatically generated_ portions of figure text, but not ones explicitly set by the user.  Search for xlabel, ylabel, title, legend, text)
- Cleaning a variable name (column headers in the CSV output (lacking its own sanitization function right now)

**Comment by jakebeal** [comment]
Fixed in #198
