### ISSUE TITLE
batch analysis graphs don't check units on X axis

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#86]
batch analysis graphs assume that MEFL conversion is possible and always label the X axis 'CFP MEFL'.
They should be checking the units in the color model, and also not calling it FP.

**Comment by lisatiberio** [comment]
Hi Jake,
I've been looking at the code. I know we are just doing FITC for now, but wouldn't we want another field in ColorModel named units that holds the units retrieved from the BeadCatalog?  This way whenever we decide to do something other than FITC, the lookup into the BeadCatalog is already in place?  A call to get_bead_peaks returns the units and actual batch used.  The file beads_to_mefl_model currently ignores the units and batch returned from get_bead_peaks.  I could store that information in the ColorModel which then can be used later as labels on plots.
Thanks,
Lisa

**Comment by jakebeal** [comment]
I agree with your assessment --- please make it so, adjusting appropriately based on what you encounter in the code.

**Comment by jakebeal** [comment]
Resolved with #104
