### ISSUE TITLE
Scale on graphs

### ISSUE THREAD

**Issue by kkiwimagi** [TASBE/TASBEFlowAnalytics#9]
As you mentioned in our meeting today, units on graphs would be useful. For example the Compensated Positive Control graph would benefit from an indication of the x-axis being in a log scale and the y axis being in a linear scale.

**Comment by jakebeal** [comment]
Also related to #140

**Comment by jakebeal** [comment]
I believe this is mostly handled at this point, but it needs a careful read-through to make certain.
