### ISSUE TITLE
Error in ColorModel/beads_to_mefl_model 

### ISSUE THREAD

**Issue by mjbrenner** [TASBE/TASBEFlowAnalytics#91]
I am getting the following error when I try to build a color model: 
![screen shot 2017-10-17 at 7 18 06 pm](https://user-images.githubusercontent.com/31046613/31694054-0cb63e9c-b370-11e7-9cb1-1ac3d6dc146a.png)

Subscript indices must either be real positive integers or logicals.

Error in ColorModel/beads_to_mefl_model (line 54)
    PeakMEFLs = PeakMEFLs((end-6):end);

Error in ColorModel/resolve (line 35)
        CM.unit_translation = beads_to_mefl_model(CM,settings,CM.BeadFile, 2, path);

Error in CM171017AJ02 (line 74)
CM=resolve(CM, settings);

**Comment by jakebeal** [comment]
If you pull from the kludge-beadcount branch, I have a patch for this bug: https://github.com/TASBE/TASBEFlowAnalytics/tree/fix/kludge-beadcount
I have not yet incorporated this into a release because I am still getting it to work correctly on octave as well.

**Comment by mjbrenner** [comment]
That did it, thanks.

**Comment by jakebeal** [comment]
Resolved with the fixing of #20.  The current release should now work with URCP-38-2K beads.
