### ISSUE TITLE
CSV serialization of analysis products

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#95]
Right now, TASBE only offers informal and ad-hoc serialization of analysis products to CSV.
In the tutorial, template_analysis/batch_template.m contains the typical serialization of high-level statistics.

For easier consumption by users, we should provide functions that serialize at least the following analysis products to CSV (in order of increasing resolution):
1. count, geo. mean, geo std.dev
2. histogram
3. collection of color-model-processed data points

The first two should be extracted from batch analysis results objects
The third should just be a (batching) wrapper around ColorModel.readfcs_compensated_MEFL function

**Comment by lisatiberio** [comment]
Hi Jake,
The function readfsc_compensated_ERF has four input parameters: a ColorModel, a string, and two flags.  How will the batching wrapper obtain this information?  Will I be given a file to parse that contains the location of a ColorModel to load, the file to convert, and the flag values?
Thanks,
Lisa

**Comment by lisatiberio** [comment]
Hi Jake,
Unless you have a strong objection, I would like to write the first two items above in a separate file for each file pair.  This would increase the number of output files, but make parsing those files easier.
Thanks,
Lisa

**Comment by jakebeal** [comment]
I do have a strong objection, because it makes "quick looks" into the CSV data to compare across samples much more difficult.

**Comment by lisatiberio** [comment]
Just pushed a fix for the broken call to writeTable.

**Comment by jakebeal** [comment]
Great: set up the pull req when you are ready.

**Comment by jakebeal** [comment]
I believe this is fully complete at this point.
