### ISSUE TITLE
Error: undefined function 'normpdf' for input arguments of type double in tutorial exercises

### ISSUE THREAD

**Issue by lisatiberio** [TASBE/TASBEFlowAnalytics#97]
Stumbled upon this error while running script "exercises" in 02_flow_compensation.

**Comment by jakebeal** [comment]
I believe this is related to #96 : a kludge patch would be to update the exercises; the true fix will likely be addressing #96.

**Comment by jakebeal** [comment]
#96 is still open, but @coverney tutorial updates have ensured there are no current bugs in the sequence.
